### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by AndyDu0116** [HaozheZhao/MIC#15] opened 2023-09-26 11:50 UTC
作者您好，非常感谢您优秀的开源工作！
我对于您的工作很感兴趣，从您的论文中了解到MMICL仅需要少量的资源就能训练出一个感知和认知能力都很强的多模态大模型，目前也想复现您的工作，但是遇到了两个问题，希望您能解答一下：
1.您在论文中写到MMICL数据集总计包含5.8M的数据，对于instructBLIP T5XXL实验使用其中的10%训练3个批次，我下载了您开源的MIC_full数据集，统计后发现其中共计3.9M行应该也就是总计的数据量吧？请问您训练使用的数据是指5.8M的10%还是MIC_Full的10%呢？另外就是这10%的数据是采样一次后训练三个批次还是每个训练批次分别采样10%呢？

2.关注到您近期重新上传了模型权重并更新了git仓库代码，使用您开源的模型权重在MME感知任务上推理得到了和榜单上相近的分数，但是在认知任务上只能得到310分和MMICL在榜单上的分数有较大的差距，在推理时我用的prompt仅包含一张图片和MME的问题描述，例如prompt='Use the image 0: <image0>图 as a visual aid to help you visual question answering rately. Here is the question about image 0:'+ question。在实验中发现不同的prompt对结果有一定影响，想请问您在推理时是怎么定义prompt的呢

再次感谢您优秀的开源工作，我也是十分敬佩，也非常想复现您的工作，希望您能给予回复，感谢。

**Comment by HaozheZhao** [comment] 2023-10-05 10:59
Hi there, I'm delighted that you're interested in our work. I hope you had a pleasant holiday. Regarding the prompt we used, please refer to the appendix of our paper on [arxiv](https://arxiv.org/abs/2309.07915). We have implemented different kinds of prompts for various tasks, but since they can be extensive, we haven't listed them here. We have updated our paper to version 2.0 and further details can be found in the Appendix.

Now, addressing your two questions: First, we trained using a sampled 10% of MIC_Full for three to four epochs. The training data we used is called MIC_sample. However, due to network issues, we haven't uploaded the entire MIC dataset to Huggingface Hub yet. Once we resolve these issues, it will be uploaded as soon as possible.

Secondly, you may have noticed that the current VLM is somewhat sensitive to prompts. For evaluating different tasks mentioned in our paper, we use slightly different prompts such as "Use image 0: <image0>{replace_token} as a visual aid for accurate answers" or "The image 0 is <image0>{replace_token}.\nGiven <image0>, answer the following question." Despite being prompt-sensitive，we discovered that MMICL performs similarly well with these prefixes. As there are evaluations involving dozens of different datasets，we are currently organizing specific evaluation code which will be released in the future.

**Comment by AndyDu0116** [comment] 2023-10-06 15:18
非常感谢您的回复，这些对我的问题有很大帮助，我会认真阅读您的paper学习相关细节。

在最近的训练中我遇到了一个十分困扰的问题就是训练过程中进程会被杀死，最后的输出是：[launch.py:428:sigkill_handler] Killing subprocess 13266，exits with return code = -9。记录训练过程中进程占用的内存发现：正常训练过程中进程仅会占用40G左右的内存，出错时进程占用的内存就会直线上升，最终占用将近1T的内存而被操作系统杀掉。实验基本环境是：deepspeed ==0.8.3 cuda==11.7 torch==11.3.1 transformers==4.28.1。不知道您在训练过程中是否遇到过这种情况，若有解决方法希望您能不吝赐教给予解答。

**Comment by HaozheZhao** [comment] 2023-10-09 02:41
Hi there, I tried to reproduce the issue you mentioned, which took some time and prevented me from responding to your concern promptly. Unfortunately, I was unable to reproduce the problem as described by you. So, it would be helpful if you could provide more detailed information about your training problem, such as at which stage the problem occurred (during training, inference, or data preprocessing). It would also be very helpful if you could specify which part of the code caused this issue.

**Closed** 2023-10-27 16:28 UTC
